Fixing an incompatibility with py3
Prior to prepending the :dolphin: string with 'b', the error while running under Python 3.5.2 would be:
TypeError: a bytes-like object is required, not 'str'